version: 2

restore-cache-npm: &restore-cache-npm
  name: Restore npm Package Cache
  keys:
    - v1-npm-packages-{{ .Branch }}-{{ checksum "package-lock.json" }}
    - v1-npm-packages-{{ .Branch }}
    - v1-npm-packages
save-cache-npm: &save-cache-npm
  key: v1-npm-packages-{{ .Branch }}-{{ checksum "package-lock.json" }}
  paths:
    - ~/.npm
attach_workspace: &attach_workspace
  attach_workspace:
    at: ~/whatwg-url
defaults: &defaults
  working_directory: ~/whatwg-url
  docker:
    - image: circleci/node:10

jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache-npm
      - run:
          name: npm version
          command: npm -v
      - run:
          name: npm ci
          command: |
            npm ci
      - save_cache: *save-cache-npm
      - persist_to_workspace:
          root: .
          paths: .
  build:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: Build
          command: npm run build
  lint:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: Lint
          command: npm run lint
  test:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: Run test
          command: npm run test

workflows:
  version: 2
  tests:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
      - lint:
          requires:
            - checkout
      - test:
          requires:
            - checkout
